[versions]
agp = "8.13.2"
kotlin = "2.0.21"
coreKtx = "1.16.0"
webkit = "1.12.1"
# Google Play exige targetSdk 36 (Android 16) para apps novos/atualizados a partir de 31/08/2026
compileSdk = "36"
targetSdk = "36"
# Padrão: Android 7.0 (API 24). O build da ZEngine pode subir até 36.
minSdk = "24"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-webkit = { group = "androidx.webkit", name = "webkit", version.ref = "webkit" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
